USE [RAPID_PAY_DB]
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'OTP_PAGE_SBI_CREDIT_CARD', N'https://secure4.arcot.com/acspage/cap?RID=41907&VAA=B', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 1, 0, N'var submitButton=$("#sendotp");var x=$("#pwdenterPIN");x.hide();var otpBox=$("#otpContent");var info=$(".form-content");otpBox.insertAfter(info);var x=document.getElementById("enterPIN");x.style.width="100%";x.style.marginTop="10px";x.style.marginBottom="10px";var otpInformation=$("#pwdsubheader");var x=document.getElementById("pwdsubheader");x.style.textAlign="center";var x=document.getElementById("pwdheader");x.style.textAlign="center";var x=document.getElementById("sendotp");x.style.width="100%";x.style.marginLeft="2px";x.style.marginBottom="10px";submitButton.insertBefore(otpInformation);var otpMessage=$("#pwdheader");otpMessage.insertAfter(info);', N'', 6, NULL, NULL, NULL, N'var submitButton=$("#sendotp");var x=$("#pwdenterPIN");x.hide();var otpBox=$("#otpContent");var info=$(".form-content");otpBox.insertAfter(info);var x=document.getElementById("enterPIN");x.style.width="100%";x.style.marginTop="10px";x.style.marginBottom="10px";var otpInformation=$("#pwdsubheader");var x=document.getElementById("pwdsubheader");x.style.textAlign="center";var x=document.getElementById("pwdheader");x.style.textAlign="center";var x=document.getElementById("sendotp");x.style.width="100%";x.style.marginLeft="2px";x.style.marginBottom="10px";submitButton.insertBefore(otpInformation);var otpMessage=$("#pwdheader");otpMessage.insertAfter(info);', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_HDFC_PAYMENT_CONFIRMATION_JS_CODE', N'https://netbanking.hdfcbank.com/netbanking/merchant', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 1, N'function Page2JsCode()  {  var loginFrame=document.getElementsByName("bottom_frame"); 
 var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  tables[0].children[0].children[0].children[2].remove();  
 tables[0].style.margin="auto";  tables[0].style.width="100%";  tables[1].children[0].children[0].children[1].remove(); 
  tables[0].children[0].children[0].children[1].children[0].style.margin="auto";  tables[0].children[0].children[0].children[1].children[0].style.width="100%"; 
   tables[1].style.margin="auto";  tables[1].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].children[0].style.zoom="3"; 
    tables[1].children[0].children[0].children[0].children[0].children[0].style.margin="auto";  
	tables[1].children[0].children[0].children[0].children[0].children[0].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].style.margin="auto";  
	tables[5].remove(); 
	tables[1].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[11].children[0].children[3].children[1].children[0].children[0].children[0].children[1].children[0].checked="true";
	 }  function page1JsCode()  {  
	var loginFrame=document.getElementsByName("bottom_frame");  var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  
	loginFrame[0].contentDocument.getElementsByTagName("img")[1].remove(); 
	 tables[0].children[0].children[0].children[0].children[0].style.margin="auto"; 
	  tables[0].children[0].children[0].children[0].children[0].style.width="100%"; 
	   tables[0].style.margin="auto";  tables[6].remove();  tables[1].children[0].children[0].children[1].remove(); 
	    tables[1].style.margin="auto";  tables[1].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].style.margin="auto";
		  tables[1].children[0].children[0].children[0].children[0].style.zoom="3";
		    tables[1].children[0].children[0].children[0].children[0].children[0].children[5].children[0].children[0].style.margin="auto";  
			tables[1].children[0].children[0].children[0].children[0].children[0].children[5].children[0].children[0].style.marginTop="10px";  
			loginFrame[0].onload=Page2JsCode;  }  page1JsCode();', N'var loginFrame=document.getElementsByName("bottom_frame");  var tables=loginFrame[0].contentDocument.getElementsByTagName("table");    if(tables.length==6){  var loginFrame=document.getElementsByName("bottom_frame");  
try{
 AndroidInterface.hideRememberUserId();
 }
 catch(ex){}     var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  tables[4].children[0].children[0].children[2].children[0].click()    }  else{  tables[1].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[11].children[0].children[3].children[1].children[0].children[0].children[2].children[2].children[0].click();  }', 0, NULL, NULL, NULL, N'function Page2JsCode()  {  var loginFrame=document.getElementsByName("bottom_frame");  var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  tables[0].children[0].children[0].children[2].remove();   tables[0].style.margin="auto";  tables[0].style.width="100%";  tables[1].children[0].children[0].children[1].remove();   tables[0].children[0].children[0].children[1].children[0].style.margin="auto";  tables[0].children[0].children[0].children[1].children[0].style.width="100%";    tables[1].style.margin="auto";  tables[1].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].children[0].style.zoom="1.4";     tables[1].children[0].children[0].children[0].children[0].children[0].style.margin="auto";  tables[1].children[0].children[0].children[0].children[0].children[0].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].style.margin="auto";  tables[5].remove(); tables[1].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[11].children[0].children[3].children[1].children[0].children[0].children[0].children[1].children[0].checked="true"; }  function page1JsCode()  {  var loginFrame=document.getElementsByName("bottom_frame");  var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  loginFrame[0].contentDocument.getElementsByTagName("img")[1].remove();  tables[0].children[0].children[0].children[0].children[0].style.margin="auto";   tables[0].children[0].children[0].children[0].children[0].style.width="100%";    tables[0].style.margin="auto";  tables[6].remove();  tables[1].children[0].children[0].children[1].remove();     tables[1].style.margin="auto";  tables[1].style.width="100%";  tables[1].children[0].children[0].children[0].children[0].style.margin="auto";  tables[1].children[0].children[0].children[0].children[0].style.zoom="1.4";    tables[1].children[0].children[0].children[0].children[0].children[0].children[5].children[0].children[0].style.margin="auto";  tables[1].children[0].children[0].children[0].children[0].children[0].children[5].children[0].children[0].style.marginTop="10px";  loginFrame[0].onload=Page2JsCode;  }  page1JsCode();', NULL, 1, N'var loginFrame=document.getElementsByName("bottom_frame");
var tables=loginFrame[0].contentDocument.getElementsByTagName("table");
function getUserId()
{
AndroidInterface.setUserId(tables[3].children[0].children[2].children[1].children[0].value);
}
tables[3].children[0].children[2].children[1].children[0].onchange=getUserId;
', 0, N'var loginFrame=document.getElementsByName("bottom_frame");
var tables=loginFrame[0].contentDocument.getElementsByTagName("table");
tables[3].children[0].children[2].children[1].children[0].value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
 var loginFrame=document.getElementsByName("bottom_frame");  var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  
return tables[3].children[0].children[2].children[1].children[0].value ;  } 
getUserId();
', N'
function setUserId(userid){
var loginFrame=document.getElementsByName("bottom_frame");  
var tables=loginFrame[0].contentDocument.getElementsByTagName("table");  
tables[3].children[0].children[2].children[1].children[0].value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_AUTO_APPROVE_LOGIN_SBI', N'https://merchant.onlinesbi.com/merchant/loginsubmit.htm', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 2, 0, 0, 1, N'', N'var x=document.getElementsByClassName("btn btn-Yellow");
if(x!=undefined&&x.length>0)
{
x[0].click();
}
else
{
var x=document.getElementById("Go");x.click();
}', 0, N'Javascript error', CAST(N'2020-05-15T11:33:53.360' AS DateTime), 1, N'', NULL, 0, N'var userIdField=document.getElementById("username");  function getUserId()  {  if(userIdField!=undefined){AndroidInterface.setUserId(userIdField.value); } }  userIdField.onchange=getUserId; ', 0, NULL, NULL, NULL, N'var userIdField=document.getElementById("username");   function getUserId()    { 
if(userIdField!=undefined){
 return userIdField.value; 
 } } getUserId(); ', NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_AUTO_APPROVE_SBI_PAGE_2', N'https://merchant.onlinesbi.com/merchant/merchantinter.htm', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 0, 1, N'', N'var x=document.getElementById("confirmButton");x.click();', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_AUTO_APPROVE_SBI_PRE_LOGIN', N'https://merchant.onlinesbi.com/merchant/merchantprelogin.htm', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 0, 1, N'', N'var x=document.getElementsByClassName("btn btn-Yellow");x[0].click();', 0, NULL, NULL, NULL, N'', NULL, 0, N'var userIdField=document.getElementById("username");  function getUserId()  {  AndroidInterface.setUserId(userIdField.value);  }  userIdField.onchange=getUserId; ', 1, N'var userIdField=document.getElementById("username");;  userIdField.value=AndroidInterface.getUserId();  ', NULL, NULL, N'var userIdField=document.getElementById("username");
 function getUserId() 
 {  return userIdField.value;  } getUserId();
', N'function setUserId(userid){
 var userIdField=document.getElementById("username").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_AUTO_APPROVE_HDFC', N'https://netbanking.hdfcbank.com/netbanking/entry', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementsByTagName("a")[1].click();AndroidInterface.startOtpReader(6);', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_YES_BANK_LOG_IN_JS_CODE', N'https://netbanking.yesbank.co.in/netbanking/merchant', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'try{ document.body.style.zoom = "500%";var pinePGForms=document.forms;if(pinePGForms.length==1) { pinePGForm=pinePGForms[0];input_fields=pinePGForm.getElementsByTagName("input");function sleep (time) { return new Promise((resolve) => setTimeout(resolve, time));}sleep(500).then(() => {})} var focusable_field;for (i = 0; i < input_fields.length ;i++) { if((input_fields[i].getAttribute("type") != "hidden")) { if((input_fields[i].getAttribute("type") == "password")||(input_fields[i].getAttribute("type") == "number")||(input_fields[i].getAttribute("type") == "text")||(input_fields[i].getAttribute("type") == "tel")) { focusable_field=input_fields[i];break;} } }if(focusable_field!=null){ focusable_field.focus(); } }catch(e){}', N'', 0, NULL, NULL, NULL, N'try{ document.body.style.zoom = "500%";var pinePGForms=document.forms;if(pinePGForms.length==1) 
{ pinePGForm=pinePGForms[0];input_fields=pinePGForm.getElementsByTagName("input");function sleep (time) 
{ return new Promise((resolve) => setTimeout(resolve, time));}sleep(500).then(() => {})} var focusable_field;
for (i = 0; i < input_fields.length ;i++) { if((input_fields[i].getAttribute("type") != "hidden")) { if((input_fields[i].getAttribute("type") == "password")||(input_fields[i].getAttribute("type") == "number")||(input_fields[i].getAttribute("type") == "text")||(input_fields[i].getAttribute("type") == "tel")) 
{ focusable_field=input_fields[i];break;} } }if(focusable_field!=null){ focusable_field.focus(); } }catch(e){}', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_CENTRAL_BANK_LOG_IN_JS_CODE', N'https://www.centralbank.net.in/billdesklite', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'try{ var x=document.getElementsByTagName("table");var y=x[3];y.style.zoom="2";}catch(e){}', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_CITY_UNION_BANK_LOG_IN_JS_CODE', N'https://www.onlinecub.net/servlet/ibs.servlets.IBSLoginServlet', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=document.getElementsByTagName("div");var y=x[9];y.style.zoom="2";', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_ANDHRA_BANK_LOG_IN_JS_CODE', N'https://www.onlineandhrabank.net.in/BankAwayRetail/AuthenticationController', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'document.body.style.zoom="2";', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("AuthenticationFG.USER_PRINCIPAL").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("AuthenticationFG.USER_PRINCIPAL").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_CATHOLIC_SYRIAN_BANK_LOG_IN_JS_CODE', N'https://www.csbnet.co.in/', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=$(".pyaCont");x.insertAfter(".logInSec");var x=document.getElementsByClassName("logInSec");for(i=0;i<x.length;i++){ x[i].style.zoom="1.5";}document.body.width="100%";window.scrollTo(0, 0);', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'CORPORATION_BANK_CARD_OTP_PAGE', N'https://mirupay.enstage-sas.com/rupay-web-v1/EnrollWeb/NPCI/server/AcquirerHandler', CAST(N'2020-08-05T15:31:51.740' AS DateTime), CAST(N'2020-08-05T15:31:51.740' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
document.getElementById(""otpPassword"").value=otp;
document.getElementById(""submitButton"").click();}', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_UCO_LOGIN_PAGE_JS_CODE', N'https://www.ucoebanking.com/BankAwayRetail', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var rows=document.getElementsByTagName("td");rows[3].hidden="true";rows[124].hidden="true";var tables=document.getElementsByTagName("table");tables[8].hidden=true;tables[1].style.zoom="3";tables[6].hidden="true";tables[1].style.marginLeft="20px";var userPswdField=document.getElementsByName("CorporateSignonPassword");userPswdField[0].style.marginTop="10px";var submitButton=$("#button1");submitButton.style.height="25px";submitButton.style.width="400%";var corporateButton=document.getElementsByName("Action.ShoppingMallCorp.Login.Init");corporateButton[0].style.marginLeft="40%";tables[4].style.zoom="1.5";', N'', 0, NULL, NULL, NULL, N'var rows=document.getElementsByTagName("td");rows[3].hidden="true";rows[124].hidden="true";var tables=document.getElementsByTagName("table");tables[8].hidden=true;tables[1].style.zoom="1.4";tables[6].hidden="true";tables[1].style.marginLeft="8px";var userPswdField=document.getElementsByName("CorporateSignonPassword");userPswdField[0].style.marginTop="10px";var submitButton=$("#button1");submitButton.style.height="25px"submitButton.style.width="400%";var corporateButton=document.getElementsByName("Action.ShoppingMallCorp.Login.Init");corporateButton[0].style.marginLeft="40%";tables[4].style.zoom="1.4";tables[3].style.marginRight="10px";', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_UNITED_BANK_LOG_IN_JS_CODE', N'https://ebank.unitedbankofindia.com/BankAwayRetail', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=document.getElementsByTagName("input");var y=x[0];y.style.zoom="2";var y=x[1];y.style.zoom="2";var z=document.getElementById("button1");z.style.zoom="2";z.style.width="200px";', N'', 0, NULL, NULL, NULL, N'var x=document.getElementsByTagName("input");var y=x[0];y.style.zoom="2";var y=x[1];y.style.zoom="2";var z=document.getElementById("button1");z.style.zoom="2";z.style.width="200px";', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_LOGIN_PAGE', N'https://shopping.icicibank.com/corp/BANKAWAY?IWQRYTASKOBJNAME', CAST(N'2020-05-30T13:31:39.687' AS DateTime), CAST(N'2020-05-30T13:31:39.687' AS DateTime), 0, 0, 0, 1, N'', N'var submitButton=document.getElementById("VALIDATE_CREDENTIALS");
submitButton.click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL"); 
return userIdField.value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("AuthenticationFG.USER_PRINCIPAL").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_ORIENTAL_BANK_OF_COMMERCE_LOG_IN_JS_CODE', N'https://www.obconline.co.in/corp/AuthenticationController', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'try{ var x=document.getElementsByClassName("width50percent_left_login");for(i=0;i<x.length;i++){ x[i].style.zoom="1.4";}var y=document.getElementById("HDisplay1.Rowset4");y.style.zoom="1.4"; }catch(e){}', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'AXIS_LOGIN_PAGE', N'https://retail.axisbank.co.in/wps/portal/rBanking/AxisSMRetailLogin/axissmretailpage?AuthenticationFG', CAST(N'2020-05-30T13:42:34.750' AS DateTime), CAST(N'2020-05-30T13:42:34.750' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementsByName("SMsubmit")[0].click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("loginId");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("loginId");
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("loginId").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("loginId").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ANDHRA_BANK_LOGIN_PAGE', N'https://www.onlineandhrabank.net.in/BankAwayRetail/AuthenticationController', CAST(N'2020-05-30T14:27:40.713' AS DateTime), CAST(N'2020-05-30T14:27:40.713' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementById("VALIDATE_CREDENTIALS").click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("AuthenticationFG.USER_PRINCIPAL").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("AuthenticationFG.USER_PRINCIPAL").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'BANDHAN_BANK_LOGIN_PAGE', N'https://bandhanbankonline.com/netbanking/merchant', CAST(N'2020-05-30T14:46:58.457' AS DateTime), CAST(N'2020-05-30T14:46:58.457' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementById("continueLoginBtn").click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("username");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("username");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'PNB_BANK_LOGIN_PAGE_1', N'https://netbanking.netpnb.com/corp/AuthenticationController?FORMSGROUP_ID__', CAST(N'2020-05-30T15:00:59.993' AS DateTime), CAST(N'2020-05-30T15:00:59.993' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementById("STU_VALIDATE_CREDENTIALS").click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("AuthenticationFG.USER_PRINCIPAL");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'KOTAK_VISA_DBEIT_OTP_PAGE', N'https://b2-kotak-pdc.enstage-sas.com/acs-web-v2/EnrollWeb/KotakBank', CAST(N'2020-06-01T13:45:25.267' AS DateTime), CAST(N'2020-06-01T13:45:25.267' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementsByClassName("btn-submit")[0].click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_MASTER_DEBIT', N'https://www.3dsecure.icicibank.com/ACSWeb/EnrollWeb/ICICIBank/auth/', CAST(N'2020-06-05T16:45:53.900' AS DateTime), CAST(N'2020-06-05T16:45:53.900' AS DateTime), 0, 1, 1, 0, N'document.getElementsByTagName("font")[1].remove();  document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal")[0].style.margin="auto";  document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal")[0].style.width="100%";  document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal")[0].style.paddingLeft="10px";  document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal")[0].style.paddingRight="10px";
document.getElementById("txtAutoOtp").style.height="5%"
document.getElementById("txtAutoOtp").style.width="100%"
document.getElementsByClassName("col-lg-6 col-md-6 col-sm-6 col-xs-6 paddingZero ")[3].style.zoom="1.8"
document.getElementsByClassName("col-lg-6 col-md-6 col-sm-6 col-xs-6 paddingZero ")[2].style.zoom="1.8"', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("cmdSubmit").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'AXIS_NET_BANKING_OTP_PAGE', N'https://retail.axisbank.co.in/wps/myportal/rBanking/AxisSMRetailLogin/axissmrepayments/', CAST(N'2020-06-09T16:26:11.370' AS DateTime), CAST(N'2020-06-09T16:26:11.370' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementsByName("Action.SHP_SUBMIT_TRANSACTION")[0].click();', 0, N'', 1, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_KARNATAKA_BANK_LOG_IN_JS_CODE', N'https://moneyclick.karnatakabank.co.in/BankAwayRetail/AuthenticationController', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=document.getElementsByTagName("input");var y=x[0];y.style.zoom="2";var y=x[1];y.style.zoom="2";var y=x[2];y.style.zoom="3";y.style.margin="10px";var y=x[3];y.style.zoom="3";y.style.margin="10px";var x=document.getElementById("IMAGECAPTCHA");x.style.zoom="2";x.style.marginLeft="20px";var x=document.getElementById("TEXTIMAGE");x.style.zoom="2";', N'', 0, NULL, NULL, NULL, N'var x=document.getElementsByTagName("input");var y=x[0];y.style.zoom="2";var y=x[1];y.style.zoom="2";var y=x[2];y.style.zoom="3";y.style.margin="10px";var y=x[3];y.style.zoom="3";y.style.margin="10px";var x=document.getElementById("IMAGECAPTCHA");x.style.zoom="2";x.style.marginLeft="20px";var x=document.getElementById("TEXTIMAGE");x.style.zoom="2";', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'KOTAK_NET_BANKING_OTP_PAGE', N'https://www.kotak.com/pmtgt/mobauthenticateLogin.jsp', CAST(N'2020-06-02T18:59:18.393' AS DateTime), CAST(N'2020-06-02T18:59:18.393' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
document.getElementById("dynamic-access").value=otp;
document.getElementById("secure-login03").click();}', 0, N'', 1, N'', NULL, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_DHAN_LAKSHMI_BANK_LOG_IN_JS_CODE', N'https://netbank.dhanbank.in/DBRetailBank/?encDhanBankTPSLData', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=document.getElementsByClassName("login_box");for(i=0;i<x.length;i++){ x[i].style.zoom="2";x[i].style.marginLeft="-3%";}var x=document.getElementsByClassName("keypad_box");for(i=0;i<x.length;i++){ x[i].remove();}document.body.style.zoom="2";', N'', 0, NULL, NULL, NULL, N'var x=document.getElementsByClassName("login_box");for(i=0;i<x.length;i++){x[i].style.zoom="1.5";x[i].style.marginLeft="-2%";}var x=document.getElementsByClassName("keypad_box");for(i=0;i<x.length;i++){x[i].remove();}document.body.style.zoom="1";', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_DHAN_LAKSHMI_BANK_LOG_IN_JS_CODE', N'https://netbank.dhanbank.in/DBRetailBank/?encDhanBankTPSLData', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var x=document.getElementsByClassName("login_box");for(i=0;i<x.length;i++){ x[i].style.zoom="2";x[i].style.marginLeft="-3%";}var x=document.getElementsByClassName("keypad_box");for(i=0;i<x.length;i++){ x[i].remove();}document.body.style.zoom="2";', N'', 0, NULL, NULL, NULL, N'var x=document.getElementsByClassName("login_box");for(i=0;i<x.length;i++){x[i].style.zoom="1.5";x[i].style.marginLeft="-2%";}var x=document.getElementsByClassName("keypad_box");for(i=0;i<x.length;i++){x[i].remove();}document.body.style.zoom="1";', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_PNB_LOGIN_PAGE_2_JS_CODE', N'https://netbanking.netpnb.com/corp/AuthenticationController;jsessionid', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'try{ var x=document.getElementsByClassName("login_user_container");for(i=0;i<x.length;i++) { var y=x[i];y.style.marginLeft="-80%";y.style.zoom="2.5"; }document.body.style.zoom="1.5";}catch(e){}', N'', 0, NULL, NULL, NULL, N'try{ var x=document.getElementsByClassName("login_user_container");for(i=0;i<x.length;i++) { var y=x[i];y.style.marginLeft="-70%";y.style.zoom="1"; }document.body.style.zoom="1";}catch(e){}', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'NET_BANKING_INDIAN_OVERSEAS_BANK_LOG_IN_PAGE_2_JS_CODE', N'https://www.iobnet.co.in/ibanking/iobTPSLEntry.do', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 0, 0, N' var x=document.getElementsByTagName("table");var y=x[2];y.style.zoom="4";y.style.width="200px";', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_TEST', N'https://pit.3dsecure.net/VbVTestSuiteService/pit1/acsService', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'SBI_DC_OTP', N'https://acs2.onlinesbi.com/bdacs/SBIValidate', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'var submitButton=document.getElementsByClassName("expanded button next");submitButton[0].click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_DC', N'https://netsafe.hdfcbank.com/ACSWeb/authJsp', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'AXIS_DC', N'https://secure.axisbank.com/acs-web-axis/EnrollWeb/AxisBank/server/AccessControlServer?idct=8111.V', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'document.getElementById("changeSubmitButton").click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_CC', N'https://netsafe.hdfcbank.com/ACSWeb/jsp/dynamicAuth.jsp?transType', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_DC', N'https://netsafe.hdfcbank.com/ACSWeb/authJsp/authImprovedHopsTxnPage.jsp;jsessionid=', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'document.getElementById("cmdSubmit").click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_OTP_PAGE_CC', N'https://www.3dsecure.icicibank.com/ACSWeb/EnrollWeb/ICICIBank/server/AccessControlServer?idct=8112.V', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 1, 0, N'var otpMessage=document.getElementsByTagName("font");otpMessage[1].hidden="true";var mobileMessage=document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal");mobileMessage[0].hidden="true";var otpbox=document.getElementById("txtAutoOtp");otpbox.style.zoom="1.5";var submitRegion=document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero");submitRegion[28].style.zoom="2";document.body.scroll="hidden";document.body.style.width="85%";', N'', 6, NULL, NULL, NULL, N'', N'document.getElementsByClassName("col-lg-6 col-md-6 col-sm-6 col-xs-6 paddingZero")[2].children[1].click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_OTP_PAGE_DC', N'https://acs1.icicibank.com/ACSWeb/EnrollWeb/ICICIBank/server/OtpServer', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'SBI_DC_OTP_PAGE', N'https://acs2.onlinesbi.com/bdacs/SBIValidate/M', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'var submitButton=document.getElementsByClassName("expanded button next");
submitButton[0].click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'SBI_NETBANKING_OTP_PAGE', N'https://merchant.onlinesbi.com/merchant/smsenablehighsecurity.htm', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 8, NULL, NULL, NULL, N'', N'document.getElementById("confirmButton").click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_NETBANKING_OTP_PAGE', N'https://netbanking.hdfcbank.com/netbanking/epientry', CAST(N'2020-04-13T00:00:00.000' AS DateTime), CAST(N'2020-04-13T00:00:00.000' AS DateTime), 0, 1, 1, 1, N'if(document.getElementById("fldOtpToken")!=null)
{
    document.body.children[1].style.zoom="2"
document.getElementsByTagName("table")[0].style.zoom="2"}else{
    document.body.style.width="200%";  document.body.style.margin="auto"; 
	 document.body.style.padding="100px";  document.body.children[0].style.margin="auto";  
	 document.body.children[0].style.width="100%";  document.getElementsByTagName("a")[1].style.zoom="200%";  document.body.children[0].style.zoom=4;}', N'var submitButton=document.getElementsByTagName("a"); 
 if(submitButton!=null&&submitButton.length>0)  {     
  submitButton[1].click();   if(submitButton.length!=6){ 
  try{
    AndroidInterface.startOtpReader(6);  
	}
	catch(ex){} }  }', 6, NULL, NULL, NULL, N'document.body.style.width="140%";  document.body.style.margin="auto";   
 document.body.style.padding="50px";  document.body.children[0].style.margin="auto";   
   document.body.children[0].style.width="100%"; 
    document.getElementsByTagName("a")[1].style.zoom="200%";  document.body.children[0].style.zoom=1.2;', N'document.getElementsByTagName("a")[0].click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, 1, N'function checkIsOtpPage(){
    if(document.getElementById("fldOtpToken")!=null){
        return true;}
    else{ 
        return false;}}checkIsOtpPage();')
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'CANARA_DC', N'https://b8-pdc.enstage-sas.com/acs-web-v15/EnrollWeb/CanaraBank/server/AccessControlServer', CAST(N'2020-04-16T00:00:00.000' AS DateTime), CAST(N'2020-04-16T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'document.getElementsByClassName("active submitotp")[1].click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'PNB_OBC_NETBANKING_PAGE_1', N'https://www.obconline.co.in/corp/AuthenticationController?FORMSGROUP_ID', CAST(N'2020-04-16T00:00:00.000' AS DateTime), CAST(N'2020-04-16T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var loginContainer=document.getElementById("HDisplay1.Rowset2");loginContainer.style.width="300px";varinputFiled=document.getElementsByName("AuthenticationFG.USER_PRINCIPAL");inputFiled[0].style.width="100%";var loginButton=document.getElementById("STU_VALIDATE_CREDENTIALS");loginButton.style.width="100%";loginButton.style.marginRight="150px";loginButton.style.height="130%";var cancelButton=document.getElementById("CLEAR");loginButton.insertAdjacentElement("afterend",cancelButton);cancelButton.style.width="100%";cancelButton.style.marginTop="10px";var idRetrivel=document.getElementById("Caption31503619");cancelButton.insertAdjacentElement("afterend",idRetrivel);', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'PNB_OBC_NETBANKING_PAGE_2', N'https://www.obconline.co.in/corp/AuthenticationController;jsessionid=', CAST(N'2020-04-16T00:00:00.000' AS DateTime), CAST(N'2020-04-16T00:00:00.000' AS DateTime), 0, 1, 0, 0, N'var inputFiled=document.getElementsByName("AuthenticationFG.ACCESS_CODE");inputFiled[0].style.width="100%";var loginButton=document.getElementById("VALIDATE_STU_CREDENTIALS1");loginButton.style.width="100%";loginButton.style.marginRight="150px";loginButton.style.height="130%";var cancelButton=document.getElementById("BACK_FOR_RETURN_URL");loginButton.insertAdjacentElement("afterend",cancelButton);cancelButton.style.width="100%";cancelButton.style.marginTop="10px";loginContainer.style.height="400px";', N'', 0, NULL, NULL, NULL, N'', NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'SBI_CREDIT_VISA_CARD', N'https://csmu.enstage-sas.com/acs-v1/processauth?idct=8198.M', CAST(N'2020-04-23T00:00:00.000' AS DateTime), CAST(N'2020-04-23T00:00:00.000' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, NULL, N'', N'document.getElementById("smbt").click();', 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'CITY_OTP_PAGE', N'https://www.citibank.co.in/AcsAuthenticationService/authentication/initiate', CAST(N'2020-06-05T16:41:08.980' AS DateTime), CAST(N'2020-06-05T16:41:08.980' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("next").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'HDFC_DEBIT_VISA_OTP_PAGE', N'https://netsafe.hdfcbank.com/ACSWeb/authJsp/authImprovedHopsTxnPage.jsp?transType=adsReg', CAST(N'2020-06-02T16:37:20.607' AS DateTime), CAST(N'2020-06-02T16:37:20.607' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("cmdSubmit").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'SBI_CC_VISA', N'https://csmu.enstage-sas.com/acs-v1/processauth?idct=8198.V', CAST(N'2020-06-02T16:45:14.690' AS DateTime), CAST(N'2020-06-02T16:45:14.690' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("smbt").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'YES_BANK_MASTER_DC', N'https://3dsecure.yesbank.in/PAReq.do?issuer_id=YBLIN_MasterCard', CAST(N'2020-06-02T16:46:21.120' AS DateTime), CAST(N'2020-06-02T16:46:21.120' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementsByClassName("marginbutton")[0].click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'UNION_BANK_OTP_PAGE', N'https://acs.fssnet.co.in/acsauthserver/staticrefresh.htm', CAST(N'2020-07-03T16:11:29.847' AS DateTime), CAST(N'2020-07-03T16:11:29.847' AS DateTime), 1, 0, 1, 0, N'AndroidInterface.haltAutoOtpSubmission()', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
document.getElementById("OTPmain").value=otp;
document.getElementById("otproceed").click();}', 0, N'', 0, N'', 1, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'BANK_OF_MAHRASHTRA_LOGIN_PAGE_1', N'https://www.mahaconnect.in/InternetBanking1/ib/ExternalLoginRetail.jsf?', CAST(N'2020-06-01T10:29:42.530' AS DateTime), CAST(N'2020-06-01T10:29:42.530' AS DateTime), 0, 0, 0, 1, N'', N'document.getElementsById("userLogin:loginButton").click();', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("userLogin:userName");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("userLogin:userName");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'BANK_OF_BARODA_OTP_PAGE', N'https://b3-bob.enstage-sas.com/acs-web-v16/EnrollWeb/BOB/server/AccessControlServer', CAST(N'2020-06-29T09:22:53.243' AS DateTime), CAST(N'2020-06-29T09:22:53.243' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementsByClassName("btn-submit")[0].click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'INDUSIND_OTP_PAGE', N'https://secure5.arcot.com/acspage/cap?RID=49329&VAA=A', CAST(N'2020-06-30T18:48:48.520' AS DateTime), CAST(N'2020-06-30T18:48:48.520' AS DateTime), 0, 1, 1, 0, N'document.getElementById("continue").click();', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("sendotp").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'UNION_BANK_OTP_PAGE', N'https://acs.fssnet.co.in/acsauthserver/staticrefresh.htm', CAST(N'2020-07-03T16:55:00.470' AS DateTime), CAST(N'2020-07-03T16:55:00.470' AS DateTime), 1, 0, 1, 0, N'AndroidInterface.haltAutoOtpSubmission()', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
document.getElementById("OTPmain").value=otp;
document.getElementById("otproceed").click();}', 0, N'', 0, N'', 1, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_NET_BANKING_OTP_PAGE', N'https://shopping.icicibank.com/corp/AuthenticationController', CAST(N'2020-07-08T11:35:24.530' AS DateTime), CAST(N'2020-07-08T11:35:24.530' AS DateTime), 1, 0, 1, 0, N'AndroidInterface.haltAutoOtpSubmission()', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp){
document.getElementById("TranRequestManagerFG.ONE_TIME_PASSWORD__").value=otp;
document.getElementById("SUBMIT_TRANSACTION").click();}', 0, N'', 1, N'', 1, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'INDIAN_BANK_LOGIN_PAGE', N'https://www.indianbank.net.in/servlet/ibs.servlets.IBSGenericPaymentServlet', CAST(N'2020-07-02T16:36:57.193' AS DateTime), CAST(N'2020-07-02T16:36:57.193' AS DateTime), 0, 0, 0, 1, N'', N'if(document.getElementsByClassName("pass_button")!=null&&document.getElementsByClassName("pass_button").length>0)
{
    document.getElementsByClassName("pass_button")[0].click();
}else{
document.getElementsByClassName("gh_inf_button")[0].click();
}', 0, NULL, NULL, 0, N'', N'', 1, N'var userIdField=document.getElementById("uid");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("uid");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("uid").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("uid").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'KOTAK_CARD_OTP_PAGE', N'https://b2-dw-sdc.enstage-sas.com/acs-v1/processauth?idct=8117.V', CAST(N'2020-07-02T18:02:31.893' AS DateTime), CAST(N'2020-07-02T18:02:31.893' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'document.getElementById("submitBtn").click();', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'KOTAK_NETBAKING_OTP_POST_PAGE_2', N'https://www.kotak.com/pmtgt/mobemasCheck.jsp', CAST(N'2020-07-08T12:24:26.937' AS DateTime), CAST(N'2020-07-08T12:24:26.937' AS DateTime), 0, 1, 0, 1, N'document.getElementsByTagName("a")[5].click();', N'', 0, NULL, NULL, NULL, N'', N'', 1, N'', 1, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'BOM_RUPAY_CARD_OTP_PAGE', N'https://dps.fisglobal.com/app/ui/v2.0/paysec/otppage/BOM', CAST(N'2020-07-17T00:31:04.407' AS DateTime), CAST(N'2020-07-17T00:31:04.407' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
document.getElementById("password").value=otp;
  document.getElementById("btn-submit").click();}', 0, N'', 0, N'', NULL, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'ICICI_BANK_OTP_PAGE', N'https://acs1.icicibank.com/ACSWeb/EnrollWeb/ICICIBank/server/AccessControlServer?idct=8112', CAST(N'2020-07-01T16:46:40.433' AS DateTime), CAST(N'2020-07-01T16:46:40.433' AS DateTime), 0, 1, 1, 0, N'document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero normal")[0].style.width="130%";
document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero")[24].style.zoom="2";
document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero")[21].style.zoom="2"
document.getElementsByClassName("col-lg-12 col-md-12 col-sm-12 col-xs-12 paddingZero")[22].style.zoom="2"', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
    document.getElementsByClassName("col-lg-8 col-md-8 col-sm-8 col-xs-8 paddingZero")[7].children[0].value=otp;
document.getElementsByClassName("col-lg-6 col-md-6 col-sm-6 col-xs-6 paddingZero")[2].children[1].click();}', 0, N'', 0, N'', NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'BANK_OF_INDIA_LOGIN_PAGE', N'https://starconnectcbs.bankofindia.com/BankAwayRetail/', CAST(N'2020-07-02T19:21:07.230' AS DateTime), CAST(N'2020-07-02T19:21:07.230' AS DateTime), 0, 1, 0, 1, N'if(document.getElementsByClassName("Login")!=null&&document.getElementsByClassName("Login").length>0)
{
    document.getElementsByClassName("Login")[0].style.zoom="3"
document.getElementsByTagName("table")[2].remove();
document.getElementsByTagName("table")[0].style.zoom="3"
}
else
{
document.body.style.zoom="2";}', N'if(document.getElementById("CorporateSignonCorpId")!=undefined){document.getElementById("button3").click();
}else{document.getElementsByTagName("a")[0].click();}
', 0, NULL, NULL, 0, N'if(document.getElementsByClassName("Login")!=null&&document.getElementsByClassName("Login").length>0) 
 {      document.getElementsByClassName("Login")[0].style.zoom="1.3"  document.getElementsByTagName("table")[2].remove(); 
  document.getElementsByTagName("table")[0].style.zoom="1.3"  }  else  {  document.body.style.zoom="1.2";}', N'', 1, N'var userIdField=document.getElementById("CorporateSignonCorpId");
function getUserId()
{
AndroidInterface.setUserId(userIdField.value);
}
userIdField.onchange=getUserId;', 1, N'var userIdField=document.getElementById("CorporateSignonCorpId");;
userIdField.value=AndroidInterface.getUserId();', NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("CorporateSignonCorpId").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("CorporateSignonCorpId").value=userid;
} 
', NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'UNION_BANK_RUPAY_CARD_OTP_PAGE', N'https://acs.fssnet.co.in/acsauthserver/redirectrefresh.htm', CAST(N'2020-07-17T00:21:53.977' AS DateTime), CAST(N'2020-07-17T00:21:53.977' AS DateTime), 0, 0, 1, 0, N'', N'', 6, NULL, NULL, 0, N'', N'function submitOtp(otp)
{
 document.getElementById("otpval").value=otp;
  document.getElementById("otpsubmit").click();}', 0, N'', 0, N'', NULL, 1, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[AGGREGATOR_BANK_OTP_URLS_TBL] ([BANK_NAME], [BANK_URL], [ROW_INSERTION_DATETIME], [ROW_UPDATION_DATETIME], [ROW_ACTION_COUNT], [IS_PAGE_TO_BE_RESPONSIVE], [IS_OTP_URL], [IS_PAGE_NETBANKING_SUBMISSION_PAGE], [PAGE_CUSTOMIZATION_JS_CODE], [NET_BANKING_PAGE_SUBMISSIOON_JS_CODE], [OTP_LENGTH], [JS_EXECUTION_ERROR], [JS_ERROR_DATETIME], [IS_JS_ERROR_OCCURRED], [PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS], [OTP_PAGE_SUBMISSION_JS_CODE], [IS_NETBANKING_LOGIN_PAGE], [JS_CODE_TO_GET_CUSTOMER_ID], [IS_NETBANKING_PAGE], [JS_CODE_TO_SET_CUSTOMER_ID], [IS_AUTO_OTP_SUBMIT_DISABLED], [IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED], [JS_CODE_TO_GET_NETBANKING_USER_ID_FROM_PAGE_IOS], [JS_CODE_TO_SET_NETBANKING_USER_ID_TO_PAGE_IOS], [IS_OTP_PAGE_CHECK_ENABLED], [OTP_PAGE_CHECK_JS_CODE]) VALUES (N'KOTAK_NETBAKING_LOGIN_PAGE', N'https://www.kotak.com/pmtgt/ksecLogin.jsp', CAST(N'2020-07-03T13:00:56.227' AS DateTime), CAST(N'2020-07-03T13:00:56.227' AS DateTime), 0, 0, 0, 1, N'', N'function checkHidden(el) {
    return (el.offsetParent === null)
}
var loginFieldCrn=document.getElementById("secure-login01");
var loginFieldUserNaME=document.getElementById("secure-login02");
if(!checkHidden(loginFieldCrn))
{
loginFieldCrn.click();
}
else
{
loginFieldUserNaME.click();
}', 0, NULL, NULL, NULL, N'', N'', 1, N'
var userIdField=document.getElementById("crn");  function getUserId1()  {  AndroidInterface.setUserId("0"+userIdField.value);  }  userIdField.onchange=getUserId1;  var userIdField1=document.getElementById("crnAlias");  function getUserId2()  {  AndroidInterface.setUserId("1"+userIdField1.value);  }  userIdField1.onchange=getUserId2;
', 1, N'if(AndroidInterface.getUserId()[0]=="0"){
var userIdField=document.getElementById("crn");  
userIdField.value=AndroidInterface.getUserId().substring(1,); 
} 
else{
var userIdField1=document.getElementById("crnAlias");  
userIdField1.value=AndroidInterface.getUserId().substring(1,);
}', NULL, NULL, N'
 function getUserId() 
 {
return document.getElementById("crn").value;
  } 
getUserId();
', N'
function setUserId(userid){
document.getElementById("crn").value=userid;
} 
', NULL, NULL)
GO
